name: Run health check
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@v2
      with:
        node-version: 17
    - uses: docker://ianwalter/puppeteer:2.0.0
      with:
        args: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
    - name: Install
      uses: docker://ianwalter/puppeteer:2.0.0
      with:
        args: pnpm install
    - name: Run health check
      uses: docker://ianwalter/puppeteer:2.0.0
      with:
        args: pnpm test:health-check
    - name: Push health check
      uses: ./actions/push-health-check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
