on:
  schedule:
  - cron: 0 0 * * *
name: Run daily test
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: Run testcases
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: test:health-check
